### ISSUE TITLE
Consider using dependabot for managing dependencies

### ISSUE THREAD

**Issue by sbshah97** [WebClub-NITK/WebClub-NITK.github.io#12]
Check out dependabot by Github. Would be very convenient to use.

**Comment by z0marlin** [comment]
Use dependabot for just vulnerability alerts and updates, or for automatically keeping the packages up to date? The former is already enabled for this repository

**Comment by sbshah97** [comment]
@Z0Marlin we can have it for the latter as well. You can always reject a version upgrade if it's not required.
