### ISSUE TITLE
Fix gmail links for club members

### ISSUE THREAD

**Issue by pvgupta24** [WebClub-NITK/WebClub-NITK.github.io#8]
Currently on hovering over a user, email links are shown as `https://webclub.nitk.ac.in/new/mananpoddarm@gmail.com`

**Comment by AdarshNaidu** [comment]
[fixed](https://github.com/WebClub-NITK/new/commit/e92ad810af90eb1ea1198131c4ec4d2692a269c0#diff-e872ef123c0abcee34a1b4292a1a17a1R21)
